// Generated by scripts/generate-codebooks.py; do not edit.
// Fixed numeric interoperability data; provenance: docs/method-13.md.
// JSON SHA-256: eb68b5ac5517cc443afc27267657ce7c68f3a1d55536cbf0741265e6767f61c2
enum StuffIt13Tables {
    private static func widths(_ text: String) -> [Int] {
        text.utf8.map { Int($0 <= 57 ? $0 - 48 : $0 - 87) }
    }
    static let firstCodeLengths: [[Int]] = [
        widths("45788999979998999999999a99aa9a9959999a999999997998999999999999999899889999999789799779999a9aaa9995987598879988557a585899999a99a99aaaaaaa9aaaaaaa9aaaaaaaaaaaaaaa9aaaaaaa99aaaaaaaaaaaaaaaa9aaaaa9aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa9aaaaaaaaaaa99aa9aaaaaaa9aaa9a956558999999aaa9aaaaaaaaaaaaaaaaaaaaa9a999a9a9a9a9aaa9a9aa999699a95"),
        widths("4778788887878798889999aa9aaaaa9959899ba9899989788899999a999a99a988777889889988787a8779999aabbba9868775777698676679666788889a9a9989aa9aa99aaaaaaa9aabaaaaaaababaa9baaaaaa99abababacabacbcacababbb9abbbccaaabbabaa9bababbbabbcbbaaabaabbcaabbcbbab9cabbbababab9a97356677888999baaacdbccbdccbccdcededfdeffedffefeffefddeffeeggfffcfa"),
        widths("6666698849898999899a8aaa9aaa9aa9998a9a9a9a9a99898999aaaa999a9a9978898999899a99898988899999aaaaa98898978898aa89888a88889999aaaaa9799aaaaa9aaaaaa99aaaaaaaa9aaaaaa9aaaaaaa999aaaaaaaaaaaaaaa9aaaa989aaaaaaaaaa9aaa9aaaaaaaaaaaaaa99aaaaaa9aaaaaa999aaaaaa99a998989466678899aaa9aaaaaaaaaaaaaaaaa7aaa7aa7777767a77a77767667766969a6a"),
        widths("266778787889899988999aa98a9a9a9969899a999a9999888889999999999aa977888899789a88788a8889899a9bab998798868887a978778a77789999ab9ba979aaabbaabaaabba9aabababaaababaa9aabaaaa9aaaababababbbacabababba8aababbbabababbb9abbabbbabbbaaaaabaabbaa9baabbaaabaaaaaa9baa8a86566778889abaabbccabccccdddddcddfecefgccdfegfhifhgffffddaecdhhiah4"),
        widths("79999999989997999999999a9a9a9a9959799999777977878877999977799999979777799799777779787999999999999787778867977875695756779899999999a9aaa99aaaaaaa9aaaaaaaaaaa9aaa9aaa99a9999aaaaaaaaaaa9aaaaaaaaa9aaa9aaa999aaaaa9a9aa9aa9aaaaaaa9aaaaaaaaaaaaaaa9aaaaaaa9a9a9aa9568877799999999999999999999999999aaaaaaaaaaaaaaaaaaaaaaa9aa5a8989"),
    ]
    static let secondCodeLengths: [[Int]] = [
        widths("456677677768788889698989998a5979698a9a8899798989886998899a899a8a8888897a699b78898a7869a99a8b9b9a9898888a99aa89888b98899a8baa8a9a899b9b9aabac9cabab9aababababaaa9998768bb9cac9bbbacbbacabaaababbb9cacbcabacbcbcbcacbcbbacabacacacabbbabbbacbcaabb9cbcabacabacaba754667778877686779899abbbcbabcbcbccccbccbcbcbdbcadaeedefegffiii9i8"),
        widths("566667777778787778888989899979886989898989898988888989899a8a899888788989798a8989898889999a9b9a9a88898889989a89888b8789999a9a9a98899a9a9a8a9a9bab9baaab9b9a9b9baa9a998a9b999bab9b9b9bababab9aabaa8a9aab9b9aab9aa99a9a9a9a9b9baa9a9b9b9b9a9b9b9b9a8b9a9a9a8a898987445666777788878899aaaaaabbaacbbccbccbccccccbcbdcdcdeeefdedeiih7g9"),
        widths("56666777687879887789999a899a8a986a8a8a99999a998989899a9a998a9ba88889799a898b9a9a89999899aaacabaa89998988a9ab8a998c8999989a9caaa87ba9ab9b7bacacab9b9cacaca9bcacab9a9a9bbc9a8cbc9cacadacacaca9aca98bacacacabac8cabaaac9bacacbca9ac9aacababac8c9c8c8babab9a8a99898743556566778887779899b9b9899bcbccddcdedededddcddcddeeddeeeefihi8ga"),
        widths("4566667767796887788869887989898969898a998a8a8989887999998a9a9a98789989997a9a99898988899a998b9baa88a88999a9ab999989888aa998ababb989ab9abb9caaacbb9bbc9b9aaaac9bab9bbbabbc9aacbbab9babab9bb98babba7cbbbbbcacbdbacbabababbbacbbabaaabacbcab9bababac9bbb9baa9baa9a974555667687899788a9aacabbbbabcbbbbbdcbcdcccdb9cd7dbdbabdffcefff6f5"),
        widths("8abbbcbbc6bca5cccccccddeddcdcdcf4a79bba967896767877888888987a9aab786788987aa87887a767998bbbabbb8b676666876a967667a656777a8b9d7egceeffggeffffffffefdeegfhehfhcedgchdheddeecdffefhehfefgcgfefgfghhffhhdeffdcgghefgffddfdghfhhhghehegfhffehfhfgffggehhffgfhfegggggc4455666777888899999aaababbbbbcccddcdceecddddecddeeedeeffdfdhhh9h7"),
    ]
    static let offsetCodeLengths: [[Int]] = [
        widths("56333333346"),
        widths("5644333334446"),
        widths("67443333344457"),
        widths("36542333446"),
        widths("67764322336"),
    ]
    static let offsetCodeSize = offsetCodeLengths.map { $0.count }
    static let metaCodes: [UInt32] = [1496, 88, 64, 192, 0, 120, 43, 20, 12, 28, 27, 11, 16, 32, 56, 24, 216, 3032, 384, 1664, 896, 3968, 1920, 1152, 128, 640, 984, 4056, 2008, 2520, 472, 4, 1, 2, 7, 3, 8]
    static let metaCodeLengths: [Int] = [11, 8, 8, 8, 8, 7, 6, 5, 5, 5, 5, 6, 5, 6, 7, 7, 9, 12, 10, 11, 11, 12, 12, 11, 11, 11, 12, 12, 12, 12, 12, 5, 2, 2, 3, 4, 5]
}
