#!/usr/bin/env python3
"""Generate Swift's fixed wire-format data; --check never changes a file."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

def generated():
    raw = (ROOT / "docs/format/method13-codebooks.json").read_bytes()
    data = json.loads(raw)
    assert len(data["presets"]) == 5
    assert len(data["meta_codes"]) == len(data["meta_lengths"]) == 37
    lines = [
        "// Generated by scripts/generate-codebooks.py; do not edit.",
        "// Fixed numeric interoperability data; provenance: docs/method-13.md.",
        "// JSON SHA-256: " + hashlib.sha256(raw).hexdigest(),
        "enum StuffIt13Tables {",
        "    private static func widths(_ text: String) -> [Int] {",
        "        text.utf8.map { Int($0 <= 57 ? $0 - 48 : $0 - 87) }",
        "    }",
    ]
    for key, name, size in [("literal", "firstCodeLengths", 321), ("match", "secondCodeLengths", 321), ("distance", "offsetCodeLengths", None)]:
        lines.append("    static let " + name + ": [[Int]] = [")
        for preset in data["presets"]:
            values = preset[key]
            assert size is None or len(values) == size
            assert all(1 <= value <= 32 for value in values)
            alphabet = '0123456789abcdefghijklmnopqrstuvwxyz'
            lines.append('        widths("' + ''.join(alphabet[v] for v in values) + '"),')
        lines.append("    ]")
    lines.append("    static let offsetCodeSize = offsetCodeLengths.map { $0.count }")
    for key, name, kind in [("meta_codes", "metaCodes", "UInt32"), ("meta_lengths", "metaCodeLengths", "Int")]:
        lines.append("    static let " + name + ": [" + kind + "] = " + str(data[key]))
    lines.extend(["}", ""])
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    target = ROOT / "Sources/unsit/StuffIt13Tables.swift"
    source = generated()
    if options.check:
        if target.read_text() != source:
            raise SystemExit("Codebooks differ: run python3 scripts/generate-codebooks.py")
    else:
        target.write_text(source)

if __name__ == "__main__":
    main()
